### ISSUE TITLE
Rphenoscate does not download

### ISSUE THREAD

**Issue by AlexTinius** [uyedaj/rphenoscate#3]
I would like to try this package with my trait data, but R won't download it. When I try:

>> install_github("uyedaj/rphenoscate") <<,
R replies with:

Downloading GitHub repo uyedaj/rphenoscate@HEAD
Skipping 1 packages not available: rphenoscape
      
√  checking for file 'C:\Users\paleo\AppData\Local\Temp\RtmpCsWeSz\remotes59b82e5819e3\uyedaj-rphenoscate-dd7de66/DESCRIPTION'
  
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path
  
Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
  
   Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
     over-long path

    ERROR
   copying to build directory failed

Error: Failed to install 'rphenoscate' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed

**Comment by uyedaj** [comment]
Hello @AlexTinius, Rphenoscate is in development and not ready for use. If you're interested in using the methods we've described elsewhere, consider using the Rphenoscape short course: https://github.com/phenoscape/scate-shortcourse or the PARAMO pipeline: https://github.com/sergeitarasov/PARAMO
